
spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/devlsy-service1;MODE=mySQL
    url: jdbc:log4jdbc:h2:tcp://localhost/~/lsy;MODE=mySQL
    username: sa
    password:
#    driver-class-name: org.h2.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

file:
  path: 'C:\test\upload\'

server:
  port: 9999

mybatis:
  mapper-locations: mybatis-mapper/**/*.xml

